openapi: 3.0.0
info:
  title: EBI LLM Analysis API Contract
  version: 1.0.0
  description: Contract for LLM provider interactions in EBI tool

paths:
  /analyze:
    post:
      summary: Analyze script component for security risks
      operationId: analyzeScript
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisRequest'
      responses:
        '200':
          description: Successful analysis
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '408':
          description: Request timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    AnalysisRequest:
      type: object
      required:
        - model
        - prompt
        - max_tokens
        - temperature
      properties:
        model:
          type: string
          description: The LLM model to use
          example: gpt-5-mini
        prompt:
          type: string
          description: The analysis prompt including script content
          maxLength: 100000
        max_tokens:
          type: integer
          minimum: 100
          maximum: 4000
          example: 2000
        temperature:
          type: number
          minimum: 0
          maximum: 1
          example: 0.3
        system_prompt:
          type: string
          description: System-level instructions for analysis

    AnalysisResponse:
      type: object
      required:
        - risk_level
        - summary
        - findings
        - model_version
        - tokens_used
      properties:
        risk_level:
          type: string
          enum:
            - none
            - info
            - low
            - medium
            - high
            - critical
        summary:
          type: string
          minLength: 1
          maxLength: 500
        findings:
          type: array
          items:
            $ref: '#/components/schemas/Finding'
        confidence:
          type: number
          minimum: 0
          maximum: 1
        model_version:
          type: string
        tokens_used:
          type: object
          properties:
            prompt_tokens:
              type: integer
            completion_tokens:
              type: integer
            total_tokens:
              type: integer

    Finding:
      type: object
      required:
        - description
        - severity
      properties:
        description:
          type: string
        severity:
          type: string
          enum:
            - none
            - info
            - low
            - medium
            - high
            - critical
        location:
          type: string
          description: Line numbers or code reference
        recommendation:
          type: string

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object